#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=key --value=$key

# Not saved by default
ynh_app_setting_set --key=password --value="$password"

#=================================================
# APP CONFIG FILES
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd "$install_dir"
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install OctoPrint=="$(ynh_app_upstream_version)"

    ynh_safe_rm "$install_dir/.cache/pip"
popd

#Logrotate has to be added now, because the app won’t start if there are no logs files
ynh_config_add_logrotate
touch /var/log/$app/$app.log
chown -R $app: "/var/log/$app"

#=================================================
# INITIALIZE APP
#=================================================
ynh_script_progression "Creating the admin account and installing plugins..."

ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/octoprint user add $admin --password $password --admin

# Install the ldap plugin
ynh_setup_source --dest_dir="$install_dir" --source_id="ldap"
ynh_hide_warnings ynh_exec_as_app "$install_dir"/venv/bin/pip install --no-build-isolation "$install_dir"/ldap.zip
ynh_safe_rm "$install_dir"/ldap.zip

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}"

yunohost service add "${app}" --description="OctoPrint main service" --log="/var/log/$app/$app.log"

#ynh_hide_warnings has to be set for the Bookworm version of fail2ban, further OS realease have this bug resoled (normally)
#ynh_hide_warnings ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-access.log" --failregex="<HOST>.* \"POST /api/auth/login HTTP/\d.\d\" 40"

if getent group dialout && ! id -Gn "${app}" | grep -qw "\bdialout\b" >/dev/null; then
	# Add user to dialout group so it can access USB serial tty.
	adduser "${app}" dialout
fi

# On Raspberry, vcgencmd is used to get info about the board
# Octoprint use it check for throttling (power lose)
vcgencmd > /dev/null
if [ $? -eq 0 ]; then
    ynh_script_progression "vcgencmd found : add user to group"
    if getent group video && ! id -Gn "${app}" | grep -qw "\bvideo\b" >/dev/null; then
	    # Add user to video group so it can access vcgencmd.
	    adduser "${app}" video
    fi
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd services..."

ynh_systemctl --service="${app}" --action="start" --wait_until="Initializing the file metadata for" --log_path="/var/log/$app/$app.log"

sleep 15

#=================================================
# END OF SCRIPT
#=================================================

cat $install_dir/config.yaml

ynh_script_progression "Installation of $app completed"
