#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --action="stop" --service="${app}"

#=================================================
# APP CONFIG FILES
#=================================================
#ynh_script_progression "Updating $app's configuration files..."

#ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd "$install_dir"
    ynh_safe_rm "$install_dir/venv"
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install OctoPrint=="$(ynh_app_upstream_version)"

    ynh_safe_rm "$install_dir/.cache/pip"
popd

#Logrotate has to be added now, because the app won’t start if there are no logs files
ynh_config_add_logrotate

#=================================================
# INITIALIZE APP
#=================================================
ynh_script_progression "Updating plugins..."

# Install the ldap plugin
ynh_setup_source --dest_dir="$install_dir" --source_id="ldap"
ynh_hide_warnings ynh_exec_as_app "$install_dir"/venv/bin/pip install --no-build-isolation "$install_dir"/ldap.zip
ynh_safe_rm "$install_dir"/ldap.zip

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}"

yunohost service add "${app}" --description="OctoPrint main service" --log="/var/log/$app/$app.log"

#ynh_hide_warnings has to be set for the Bookworm version of fail2ban, further OS realease have this bug resoled (normally)
#ynh_hide_warnings ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-access.log" --failregex="<HOST>.* \"POST /api/auth/login HTTP/\d.\d\" 40"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd services..."

ynh_systemctl --service="${app}" --action="start" --wait_until="Initializing the file metadata for" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
